# Generated by Django 4.1.7 on 2026-02-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('octofit_tracker', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='calories',
            field=models.IntegerField(default=0),
        ),
    ]
